---
name: preprod release

on:
  workflow_dispatch:
  push:
    branches:
      - preprod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get data from repository
        uses: actions/checkout@v4

      - run: docker build --target build -t mkdocs-builder .

      - run: docker container run --rm -v ./site:/app/site mkdocs-builder

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-artifact@v4 # or specific "vX.X.X" version tag for this action
        with:
          path: site/
          name: notredoc
  deploy:
    runs-on: 
      - self-hosted
      - profy12-server
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: /var/www/html
          name: notredoc
